### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'doc/example.md'

### ISSUE THREAD

**Issue by dnesting** [mkrakowitzer/actions-makepdfs#1]
I'm overriding `markdown_dir`, because my markdown files aren't in `doc/`, but when I attempt this action, I get:

```
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'doc/example.md'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at /makepdfs.js:100:19
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

I suspect the error is a hard-coded `'doc/'` instead of `mddir` here:

https://github.com/mkrakowitzer/actions-makepdfs/blob/765f279219462ef05c533d9555962051e2a13518/makepdfs.js#L100

**Comment by mkrakowitzer** [comment]
fixed
